### ISSUE TITLE
Question about the feature extractor

### ISSUE THREAD

**Issue by lemonsweetie** [declare-lab/Multimodal-Infomax#10]
Hi, I am confused about the feature extractor in your paper. As I know, COVAREP and P2FA are both feature extractor for acoustic, but you use them for visual and acoustic.

**Comment by Clement25** [comment]
Yes, that should be a typo and we are sorry for that. Visual features are extracted with Facet as mentioned in https://arxiv.org/pdf/1906.00295.pdf

**Comment by lemonsweetie** [comment]
Thanks a lot!
