### ISSUE TITLE
Any details of processing the raw dataset

### ISSUE THREAD

**Issue by hcliucs** [declare-lab/Multimodal-Infomax#14]
Dear authors, 

There is no details of how to get the features of the raw dataset and no explanations of the extracted features. Can you provide the details？

Thanks!

**Comment by Clement25** [comment]
The shared dataset is already processed. You can directly input that into the model.

see 
https://github.com/declare-lab/Multimodal-Infomax/blob/cd0774c5a712ca5f1a5497dbf27dde11cade7434/src/create_dataset.py#L59

The hard-coded file name is the same as the shared dataset name without division. The code will automatically divide the whole dataset into train/dev/test splits.
