### ISSUE TITLE
Can I use this work for just audio and text modalities?

### ISSUE THREAD

**Issue by anuragrawal2024** [declare-lab/Multimodal-Infomax#15]
Hi All,

I am working on a sentiment analysis project where I am trying to recognize sentiments in dyadic conversations. I only have access to audio and text data and don't have image/video data. Do you think I can use this work for my project? Is the code written in such a way that you can pick and choose a combination of modalities?

Thank you for your help!

**Comment by Clement25** [comment]
Yes it can be used, but you may need to remove the code segments regarding the visual modality.

**Comment by anuragrawal2024** [comment]
Thanks @Clement25! I'll give it a try.
