### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by Thealove** [declare-lab/Multimodal-Infomax#21]
Hello, I encountered some issues while configuring the environment. It seems that there is an incompatibility between torch 1.7.0 and torchvision 0.4.2. What should I do to resolve this?

**Comment by Clement25** [comment]
I remember torchvision is not imported in the project, so you can firstly try running without it.

**Comment by Thealove** [comment]
> I remember torchvision is not imported in the project, so you can firstly try running without it.

Thank you for your reply, the problem has been solved, may I ask how your dataset converts video and voice into pkl files

**Comment by Clement25** [comment]
> > I remember torchvision is not imported in the project, so you can firstly try running without it.
> 
> Thank you for your reply, the problem has been solved, may I ask how your dataset converts video and voice into pkl files

You can extract features according to related papers, and save the results as numpy arrays into the `pkl.` file.
