### ISSUE TITLE
acc/f1 calculation

### ISSUE THREAD

**Issue by cyZhu-upup** [declare-lab/Multimodal-Infomax#3]
Hi, thank you for your great work! However, there seems to be a little mistake. accuracy_score, f1_score imported from sklearn.metrics should be:
```python
f1_score / accuracy_score(y_true, y_pred)
```
which is from
https://github.com/declare-lab/Multimodal-Infomax/tree/main/src/utils/eval_metrics.py#L47

you can check it in [https://scikit-learn.org/0.21/modules/classes.html#sklearn-metrics-metrics](url)

**Comment by Clement25** [comment]
Thanks for your pointing out. We have rerun the experiments and found f1_score is even higher. Therefore we preserve the previous results.
