### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by GalioMax** [declare-lab/Multimodal-Infomax#6]
Hi, your work is really great and inspiring to me, but after reading your paper, I am still confused about some parts of it. Does LBA include lld in formula 4 (LBA=lld + H(y)), or is lld just used to update the parameters of the predictor in the first stage of training, and does not need to be used for LBA calculation? Looking forward to your reply.

**Comment by Clement25** [comment]
Hi, lld is part of LBA to update the predictor concurrently in the first stage.
