### ISSUE TITLE
The sota of MOSET dataset

### ISSUE THREAD

**Issue by qimg412** [declare-lab/Multimodal-Infomax#7]
hello, could you tell me how to set the model to get the sota more closer to the sota of the paper,I have try your parameters,but it does not work effectively

**Comment by Clement25** [comment]
Hello. You can try different weights for contrastive loss. The results may vary on different GPUs for hardware conditions.

**Comment by qimg412** [comment]
Thanks a lot!I will try it by your methods



---- Replied Message ----
| From | Wei Han ***@***.***> |
| Date | 09/06/2022 20:05 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [declare-lab/Multimodal-Infomax] The sota of MOSET dataset (Issue #7) |

Closed #7 as completed.
